apiVersion: monitoring.coreos.com/v1
kind: Probe

metadata:
  name: demo-probe
  namespace: prometheus-operator

spec:
  prober:
    path: /probe
    url: prometheus-blackbox-exporter:9115
  module: http_2xx
  targets:
    staticConfig:
      static:
        - "https://google.co.uk"
