name: 'Setup runner'
description: 'Setup the runner environment'

runs:
  using: "composite"

  steps:
    - name: "Add cluster CA certificate"
      shell: bash
      run: "echo $CLUSTER_CA_CERT_DATA > cluster.cert.pem && sudo mkdir /usr/local/share/ca-certificates/extra && sudo cp cluster.cert.pem /usr/local/share/ca-certificates/extra/cluster.cert.crt && sudo update-ca-certificates"
    - name: "Generate and install kubeconfig"
      working-directory: ./terraform
      shell: bash
      run: |
        ./cluster-config-write.sh
        mkdir ~/.kube
        cp cluster.yml ~/.kube/config
    - name: "Setup node"
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: "Setup kubectl"
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.4'
    - name: "Terraform setup"
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6