resource "kubernetes_secret" "ocis_config" {
  metadata {
    name      = "ocis-config"
    namespace = kubernetes_namespace.ocis.metadata[0].name
  }

  data = {
    # MICRO_REGISTRY                                         = "kubernetes"
    # GATEWAY_LOG_COLOR                                      = "false"
    # GATEWAY_LOG_LEVEL                                      = "info"
    # GATEWAY_LOG_PRETTY                                     = "false"
    # GATEWAY_TRACING_ENABLED                                = "false"
    # GATEWAY_TRACING_TYPE                                   = "jaeger"
    # GATEWAY_TRACING_ENDPOINT                               = ""
    # GATEWAY_TRACING_COLLECTOR                              = ""
    # GATEWAY_DEBUG_PPROF                                    = "false"
    # GATEWAY_GRPC_ADDR                                      = "0.0.0.0:9142"
    # GATEWAY_DEBUG_ADDR                                     = "0.0.0.0:9143"
    OCIS_REVA_GATEWAY                                      = "127.0.0.1:9142"
    GATEWAY_FRONTEND_PUBLIC_URL                            = "https://ocis.${var.server_base_domain}"
    # GATEWAY_USERS_ENDPOINT                                 = "users:9144"
    # GATEWAY_GROUPS_ENDPOINT                                = "groups:9160"
    # GATEWAY_AUTH_BASIC_ENDPOINT                            = "authbasic:9146"
    # GATEWAY_AUTH_MACHINE_ENDPOINT                          = "authmachine:9166"
    # GATEWAY_PERMISSIONS_ENDPOINT                           = "settings:9191"
    # GATEWAY_SHARING_ENDPOINT                               = "sharing:9150"
    # GATEWAY_STORAGE_PUBLIC_LINK_ENDPOINT                   = "storagepubliclink:9178"
    # GATEWAY_STORAGE_USERS_ENDPOINT                         = "storageusers:9157"
    # GATEWAY_STORAGE_SHARES_ENDPOINT                        = "storageshares:9154"
    # GATEWAY_APP_REGISTRY_ENDPOINT                          = "appregistry:9242"
    # GATEWAY_STAT_CACHE_STORE                               = "noop"
    # GATEWAY_PROVIDER_CACHE_STORE                           = "noop"
    # GATEWAY_CREATE_HOME_CACHE_STORE                        = "memory"
    GATEWAY_STORAGE_USERS_MOUNT_ID                         = "3081f183-2e58-4f6f-8bb1-900a4152058a" # *****
    GATEWAY_JWT_SECRET                                     = random_password.jwt_secret.result
    OCIS_TRANSFER_SECRET                                   = random_password.transfer_secret.result
    # POSTPROCESSING_LOG_COLOR                               = "false"
    # POSTPROCESSING_LOG_LEVEL                               = "info"
    # POSTPROCESSING_LOG_PRETTY                              = "false"
    # POSTPROCESSING_DEBUG_PPROF                             = "false"
    # POSTPROCESSING_DEBUG_ADDR                              = "0.0.0.0:9255"
    # POSTPROCESSING_EVENTS_ENDPOINT                         = "nats:9233"
    # POSTPROCESSING_STORE                                   = "nats-js"
    # POSTPROCESSING_STORE_NODES                             = "nats:9233"
    # FRONTEND_LOG_COLOR                                     = "false"
    # FRONTEND_LOG_LEVEL                                     = "info"
    # FRONTEND_LOG_PRETTY                                    = "false"
    # FRONTEND_TRACING_ENABLED                               = "false"
    # FRONTEND_TRACING_TYPE                                  = "jaeger"
    # FRONTEND_TRACING_ENDPOINT                              = ""
    # FRONTEND_TRACING_COLLECTOR                             = ""
    # FRONTEND_DEBUG_PPROF                                   = "false"
    # FRONTEND_HTTP_ADDR                                     = "0.0.0.0:9140"
    # FRONTEND_DEBUG_ADDR                                    = "0.0.0.0:9141"
    FRONTEND_PUBLIC_URL                                    = "https://ocis.${var.server_base_domain}"
    # OCIS_REVA_GATEWAY                                      = "gateway:9142"
    OCIS_LDAP_SERVER_WRITE_ENABLED                         = "false"
    FRONTEND_READONLY_USER_ATTRIBUTES                      = ""
    FRONTEND_JWT_SECRET                                    = random_password.jwt_secret.result
    FRONTEND_APP_HANDLER_INSECURE                          = "false"
    FRONTEND_ARCHIVER_INSECURE                             = "false"
    FRONTEND_OCS_PUBLIC_WRITEABLE_SHARE_MUST_HAVE_PASSWORD = "false"
    FRONTEND_SEARCH_MIN_LENGTH                             = "3"
    FRONTEND_ENABLE_RESHARING                              = "true"
    FRONTEND_ARCHIVER_MAX_SIZE                             = "1.073741824e+09"
    FRONTEND_ARCHIVER_MAX_NUM_FILES                        = "10000"
    FRONTEND_OCS_STAT_CACHE_STORE                          = "noop"
    OCIS_EDITION                                           = "Community"
    FRONTEND_MACHINE_AUTH_API_KEY                          = random_password.machine_auth_api_key.result
    OCIS_TRANSFER_SECRET                                   = random_password.transfer_secret.result
    # USERS_LOG_COLOR                                        = "false"
    # USERS_LOG_LEVEL                                        = "info"
    # USERS_LOG_PRETTY                                       = "false"
    # USERS_TRACING_ENABLED                                  = "false"
    # USERS_TRACING_TYPE                                     = "jaeger"
    # USERS_TRACING_ENDPOINT                                 = ""
    # USERS_TRACING_COLLECTOR                                = ""
    # USERS_DEBUG_PPROF                                      = "false"
    # USERS_GRPC_ADDR                                        = "0.0.0.0:9144"
    # USERS_DEBUG_ADDR                                       = "0.0.0.0:9145"
    USERS_LDAP_INSECURE                                    = "false"
    USERS_LDAP_USER_BASE_DN                                = "ou=people,dc=idm,dc=${var.server_base_domain}"
    USERS_LDAP_GROUP_BASE_DN                               = "ou=groups,dc=idm,dc=${var.server_base_domain}"
    USERS_LDAP_USER_SCOPE                                  = "sub"
    USERS_LDAP_GROUP_SCOPE                                 = "sub"
    USERS_LDAP_USER_SUBSTRING_FILTER_TYPE                  = "any"
    USERS_LDAP_USER_FILTER                                 = ""
    USERS_LDAP_GROUP_FILTER                                = ""
    USERS_LDAP_USER_OBJECTCLASS                            = "inetOrgPerson"
    USERS_LDAP_GROUP_OBJECTCLASS                           = "groupOfNames"
    USERS_LDAP_USER_SCHEMA_ID                              = "uid"
    USERS_LDAP_GROUP_SCHEMA_ID                             = "cn"
    USERS_LDAP_USER_SCHEMA_ID_IS_OCTETSTRING               = "false"
    USERS_LDAP_GROUP_SCHEMA_ID_IS_OCTETSTRING              = "false"
    USERS_LDAP_USER_SCHEMA_MAIL                            = "mail"
    USERS_LDAP_GROUP_SCHEMA_MAIL                           = "mail"
    USERS_LDAP_USER_SCHEMA_DISPLAYNAME                     = "displayname"
    USERS_LDAP_GROUP_SCHEMA_DISPLAYNAME                    = "cn"
    USERS_LDAP_USER_SCHEMA_USERNAME                        = "uid"
    USERS_LDAP_USER_TYPE_ATTRIBUTE                         = "ownCloudUserType"
    USERS_LDAP_GROUP_SCHEMA_GROUPNAME                      = "cn"
    USERS_LDAP_GROUP_SCHEMA_MEMBER                         = "member"
    USERS_LDAP_USER_ENABLED_ATTRIBUTE                      = "ownCloudUserEnabled"
    USERS_LDAP_DISABLE_USER_MECHANISM                      = "group"
    USERS_LDAP_DISABLED_USERS_GROUP_DN                     = "cn=app_disabled,ou=groups,dc=idm,dc=${var.server_base_domain}"
    USERS_LDAP_URI                                         = "ldaps://idm.${var.server_base_domain}"
    USERS_LDAP_CACERT                                      = ""
    USERS_LDAP_BIND_DN                                     = "uid=${data.terraform_remote_state.openldap.outputs.admin_username},ou=people,dc=idm,dc=${var.server_base_domain}"
    USERS_LDAP_BIND_PASSWORD                               = data.terraform_remote_state.openldap.outputs.admin_password
    USERS_IDP_URL                                          = "https://idp.${var.server_base_domain}/realms/${var.server_base_domain}"
    # OCIS_REVA_GATEWAY                                      = "gateway:9142"
    USERS_JWT_SECRET                                       = random_password.jwt_secret.result
    # STORAGE_SHARES_LOG_COLOR                               = "false"
    # STORAGE_SHARES_LOG_LEVEL                               = "info"
    # STORAGE_SHARES_LOG_PRETTY                              = "false"
    # STORAGE_SHARES_TRACING_ENABLED                         = "false"
    # STORAGE_SHARES_TRACING_TYPE                            = "jaeger"
    # STORAGE_SHARES_TRACING_ENDPOINT                        = ""
    # STORAGE_SHARES_TRACING_COLLECTOR                       = ""
    # STORAGE_SHARES_DEBUG_PPROF                             = "false"
    # STORAGE_SHARES_GRPC_ADDR                               = "0.0.0.0:9154"
    # STORAGE_SHARES_DEBUG_ADDR                              = "0.0.0.0:9156"
    # STORAGE_SHARES_USER_SHARE_PROVIDER_ENDPOINT            = "sharing:9150"
    # OCIS_REVA_GATEWAY                                      = "gateway:9142"
    STORAGE_SHARES_JWT_SECRET                              = random_password.jwt_secret.result
    # WEBDAV_LOG_COLOR                                       = "false"
    # WEBDAV_LOG_LEVEL                                       = "info"
    # WEBDAV_LOG_PRETTY                                      = "false"
    # WEBDAV_TRACING_ENABLED                                 = "false"
    # WEBDAV_TRACING_TYPE                                    = "jaeger"
    # WEBDAV_TRACING_ENDPOINT                                = ""
    # WEBDAV_TRACING_COLLECTOR                               = ""
    # WEBDAV_DEBUG_PPROF                                     = "false"
    # WEBDAV_HTTP_ADDR                                       = "0.0.0.0:9115"
    # WEBDAV_DEBUG_ADDR                                      = "0.0.0.0:9119"
    OCIS_PUBLIC_URL                                        = "https://ocis.${var.server_base_domain}"
    # OCIS_REVA_GATEWAY                                      = "gateway:9142"
    # SETTINGS_LOG_COLOR                                     = "false"
    # SETTINGS_LOG_LEVEL                                     = "info"
    # SETTINGS_LOG_PRETTY                                    = "false"
    # SETTINGS_TRACING_ENABLED                               = "false"
    # SETTINGS_TRACING_TYPE                                  = "jaeger"
    # SETTINGS_TRACING_ENDPOINT                              = ""
    # SETTINGS_TRACING_COLLECTOR                             = ""
    # SETTINGS_DEBUG_PPROF                                   = "false"
    # SETTINGS_HTTP_ADDR                                     = "0.0.0.0:9190"
    # SETTINGS_GRPC_ADDR                                     = "0.0.0.0:9191"
    # SETTINGS_DEBUG_ADDR                                    = "0.0.0.0:9194"
    # STORAGE_GATEWAY_GRPC_ADDR                              = "storagesystem:9215"
    # STORAGE_GRPC_ADDR                                      = "storagesystem:9215"
    SETTINGS_JWT_SECRET                                    = random_password.jwt_secret.result
    OCIS_SYSTEM_USER_API_KEY                               = random_uuid.storage_system_user_id.result
    OCIS_SYSTEM_USER_ID                                    = random_password.storage_system_api_key.result
    # NATS_LOG_COLOR                                         = "false"
    # NATS_LOG_LEVEL                                         = "info"
    # NATS_LOG_PRETTY                                        = "false"
    # NATS_DEBUG_PPROF                                       = "false"
    # NATS_NATS_HOST                                         = "0.0.0.0"
    # NATS_NATS_PORT                                         = "9233"
    # NATS_DEBUG_ADDR                                        = "0.0.0.0:9234"
    # STORAGE_SYSTEM_LOG_COLOR                               = "false"
    # STORAGE_SYSTEM_LOG_LEVEL                               = "info"
    # STORAGE_SYSTEM_LOG_PRETTY                              = "false"
    # STORAGE_SYSTEM_TRACING_ENABLED                         = "false"
    # STORAGE_SYSTEM_TRACING_TYPE                            = "jaeger"
    # STORAGE_SYSTEM_TRACING_ENDPOINT                        = ""
    # STORAGE_SYSTEM_TRACING_COLLECTOR                       = ""
    # STORAGE_SYSTEM_DEBUG_PPROF                             = "false"
    # STORAGE_SYSTEM_GRPC_ADDR                               = "0.0.0.0:9215"
    # STORAGE_SYSTEM_DEBUG_ADDR                              = "0.0.0.0:9217"
    # STORAGE_SYSTEM_HTTP_ADDR                               = "0.0.0.0:9216"
    # STORAGE_SYSTEM_DATA_SERVER_URL                         = "http://storagesystem:9216/data"
    # OCIS_REVA_GATEWAY                                      = "gateway:9142"
    # STORAGE_SYSTEM_DRIVER                                  = "ocis"
    # STORAGE_SYSTEM_OCIS_METADATA_BACKEND                   = "messagepack"
    # STORAGE_SYSTEM_CACHE_STORE                             = "noop"
    STORAGE_SYSTEM_JWT_SECRET                              = random_password.storage_system_jwt_secret.result
    OCIS_SYSTEM_USER_API_KEY                               = random_uuid.storage_system_user_id.result
    OCIS_SYSTEM_USER_ID                                    = random_password.storage_system_api_key.result
    # AUTH_MACHINE_LOG_COLOR                                 = "false"
    # AUTH_MACHINE_LOG_LEVEL                                 = "info"
    # AUTH_MACHINE_LOG_PRETTY                                = "false"
    # AUTH_MACHINE_TRACING_ENABLED                           = "false"
    # AUTH_MACHINE_TRACING_TYPE                              = "jaeger"
    # AUTH_MACHINE_TRACING_ENDPOINT                          = ""
    # AUTH_MACHINE_TRACING_COLLECTOR                         = ""
    # AUTH_MACHINE_DEBUG_PPROF                               = "false"
    # AUTH_MACHINE_GRPC_ADDR                                 = "0.0.0.0:9166"
    # AUTH_MACHINE_DEBUG_ADDR                                = "0.0.0.0:9167"
    # OCIS_REVA_GATEWAY                                      = "gateway:9142"
    AUTH_MACHINE_JWT_SECRET                                = random_password.jwt_secret.result
    AUTH_MACHINE_API_KEY                                   = random_password.machine_auth_api_key.result
    # GROUPS_LOG_COLOR                                       = "false"
    # GROUPS_LOG_LEVEL                                       = "info"
    # GROUPS_LOG_PRETTY                                      = "false"
    # GROUPS_TRACING_ENABLED                                 = "false"
    # GROUPS_TRACING_TYPE                                    = "jaeger"
    # GROUPS_TRACING_ENDPOINT                                = ""
    # GROUPS_TRACING_COLLECTOR                               = ""
    # GROUPS_DEBUG_PPROF                                     = "false"
    # GROUPS_GRPC_ADDR                                       = "0.0.0.0:9160"
    # GROUPS_DEBUG_ADDR                                      = "0.0.0.0:9161"
    GROUPS_LDAP_INSECURE                                   = "false"
    GROUPS_LDAP_USER_BASE_DN                               = "ou=people,dc=idm,dc=${var.server_base_domain}"
    GROUPS_LDAP_GROUP_BASE_DN                              = "ou=groups,dc=idm,dc=${var.server_base_domain}"
    GROUPS_LDAP_USER_SCOPE                                 = "sub"
    GROUPS_LDAP_GROUP_SCOPE                                = "sub"
    GROUPS_LDAP_USER_SUBSTRING_FILTER_TYPE                 = "any"
    GROUPS_LDAP_USER_FILTER                                = ""
    GROUPS_LDAP_GROUP_FILTER                               = ""
    GROUPS_LDAP_USER_OBJECTCLASS                           = "inetOrgPerson"
    GROUPS_LDAP_GROUP_OBJECTCLASS                          = "groupOfNames"
    GROUPS_LDAP_USER_SCHEMA_ID                             = "uid"
    GROUPS_LDAP_GROUP_SCHEMA_ID                            = "cn"
    GROUPS_LDAP_USER_SCHEMA_ID_IS_OCTETSTRING              = "false"
    GROUPS_LDAP_GROUP_SCHEMA_ID_IS_OCTETSTRING             = "false"
    GROUPS_LDAP_USER_SCHEMA_MAIL                           = "mail"
    GROUPS_LDAP_GROUP_SCHEMA_MAIL                          = "mail"
    GROUPS_LDAP_USER_SCHEMA_DISPLAYNAME                    = "displayname"
    GROUPS_LDAP_GROUP_SCHEMA_DISPLAYNAME                   = "cn"
    GROUPS_LDAP_USER_SCHEMA_USERNAME                       = "uid"
    GROUPS_LDAP_GROUP_SCHEMA_GROUPNAME                     = "cn"
    GROUPS_LDAP_GROUP_SCHEMA_MEMBER                        = "member"
    GROUPS_LDAP_URI                                        = "ldaps://idm.${var.server_base_domain}"
    GROUPS_LDAP_CACERT                                     = ""
    GROUPS_LDAP_BIND_DN                                    = "uid=${data.terraform_remote_state.openldap.outputs.admin_username},ou=people,dc=idm,dc=${var.server_base_domain}"
    GROUPS_LDAP_BIND_PASSWORD                              = data.terraform_remote_state.openldap.outputs.admin_password
    GROUPS_IDP_URL                                         = "https://idp.${var.server_base_domain}/realms/${var.server_base_domain}"
    # OCIS_REVA_GATEWAY                                      = "gateway:9142"
    GROUPS_JWT_SECRET                                      = random_password.jwt_secret.result
    # WEB_LOG_COLOR                                          = "false"
    # WEB_LOG_LEVEL                                          = "info"
    # WEB_LOG_PRETTY                                         = "false"
    # WEB_TRACING_ENABLED                                    = "false"
    # WEB_TRACING_TYPE                                       = "jaeger"
    # WEB_TRACING_ENDPOINT                                   = ""
    # WEB_TRACING_COLLECTOR                                  = ""
    # WEB_DEBUG_PPROF                                        = "false"
    # WEB_HTTP_ADDR                                          = "0.0.0.0:9100"
    # WEB_DEBUG_ADDR                                         = "0.0.0.0:9104"
    WEB_OIDC_AUTHORITY                                     = "https://idp.${var.server_base_domain}/realms/${var.server_base_domain}"
    WEB_OIDC_CLIENT_ID                                     = "ocis-web"
    WEB_UI_THEME_SERVER                                    = "https://ocis.${var.server_base_domain}"
    WEB_UI_CONFIG_SERVER                                   = "https://ocis.${var.server_base_domain}"
    WEB_OPTION_CONTEXTHELPERS_READ_MORE                    = "true"
    WEB_GATEWAY_GRPC_ADDR                                  = "gateway:9142"
    WEB_JWT_SECRET                                         = random_password.jwt_secret.result
    # APP_REGISTRY_LOG_COLOR                                 = "false"
    # APP_REGISTRY_LOG_LEVEL                                 = "info"
    # APP_REGISTRY_LOG_PRETTY                                = "false"
    # APP_REGISTRY_TRACING_ENABLED                           = "false"
    # APP_REGISTRY_TRACING_TYPE                              = "jaeger"
    # APP_REGISTRY_TRACING_ENDPOINT                          = ""
    # APP_REGISTRY_TRACING_COLLECTOR                         = ""
    # APP_REGISTRY_DEBUG_PPROF                               = "false"
    # APP_REGISTRY_GRPC_ADDR                                 = "0.0.0.0:9242"
    # APP_REGISTRY_DEBUG_ADDR                                = "0.0.0.0:9243"
    # OCIS_REVA_GATEWAY                                      = "gateway:9142"
    APP_REGISTRY_JWT_SECRET                                = random_password.jwt_secret.result
    # SHARING_LOG_COLOR                                      = "false"
    # SHARING_LOG_LEVEL                                      = "info"
    # SHARING_LOG_PRETTY                                     = "false"
    # SHARING_TRACING_ENABLED                                = "false"
    # SHARING_TRACING_TYPE                                   = "jaeger"
    # SHARING_TRACING_ENDPOINT                               = ""
    # SHARING_TRACING_COLLECTOR                              = ""
    # SHARING_DEBUG_PPROF                                    = "false"
    # SHARING_GRPC_ADDR                                      = "0.0.0.0:9150"
    # SHARING_DEBUG_ADDR                                     = "0.0.0.0:9151"
    # OCIS_REVA_GATEWAY                                      = "gateway:9142"
    # SHARING_EVENTS_ENDPOINT                                = "nats:9233"
    SHARING_JWT_SECRET                                     = random_password.jwt_secret.result
    # SHARING_PUBLIC_WRITEABLE_SHARE_MUST_HAVE_PASSWORD      = "false"
    # SHARING_USER_DRIVER                                    = "jsoncs3"
    # SHARING_USER_JSONCS3_PROVIDER_ADDR                     = "storagesystem:9215"
    SHARING_USER_JSONCS3_SYSTEM_USER_API_KEY               = random_uuid.storage_system_user_id.result
    SHARING_USER_JSONCS3_SYSTEM_USER_ID                    = random_password.storage_system_api_key.result
    # SHARING_PUBLIC_DRIVER                                  = "jsoncs3"
    # SHARING_PUBLIC_JSONCS3_PROVIDER_ADDR                   = "storagesystem:9215"
    SHARING_PUBLIC_JSONCS3_SYSTEM_USER_API_KEY             = random_uuid.storage_system_user_id.result
    # AUDIT_LOG_COLOR                                        = "false"
    # AUDIT_LOG_LEVEL                                        = "info"
    # AUDIT_LOG_PRETTY                                       = "false"
    # AUDIT_DEBUG_PPROF                                      = "false"
    # AUDIT_DEBUG_ADDR                                       = "0.0.0.0:9229"
    # AUDIT_EVENTS_ENDPOINT                                  = "nats:9233"
    # AUDIT_LOG_TO_CONSOLE                                   = "true"
    # OCS_LOG_COLOR                                          = "false"
    # OCS_LOG_LEVEL                                          = "info"
    # OCS_LOG_PRETTY                                         = "false"
    # OCS_TRACING_ENABLED                                    = "false"
    # OCS_TRACING_TYPE                                       = "jaeger"
    # OCS_TRACING_ENDPOINT                                   = ""
    # OCS_TRACING_COLLECTOR                                  = ""
    # OCS_DEBUG_PPROF                                        = "false"
    # OCS_HTTP_ADDR                                          = "0.0.0.0:9110"
    # OCS_DEBUG_ADDR                                         = "0.0.0.0:9114"
    OCS_IDM_ADDRESS                                        = "https://idp.${var.server_base_domain}/realms/${var.server_base_domain}"
    # OCIS_REVA_GATEWAY                                      = "gateway:9142"
    OCS_JWT_SECRET                                         = random_password.jwt_secret.result
    OCS_MACHINE_AUTH_API_KEY                               = random_password.machine_auth_api_key.result
    # USERLOG_LOG_COLOR                                      = "false"
    # USERLOG_LOG_LEVEL                                      = "info"
    # USERLOG_LOG_PRETTY                                     = "false"
    # USERLOG_DEBUG_PPROF                                    = "false"
    # USERLOG_HTTP_ADDR                                      = "0.0.0.0=8080"
    # USERLOG_DEBUG_ADDR                                     = "0.0.0.0:9210"
    # USERLOG_STORE                                          = "nats-js"
    # USERLOG_STORE_NODES                                    = "nats:9233"
    # USERLOG_EVENTS_ENDPOINT                                = "nats:9233"
    # OCIS_REVA_GATEWAY                                      = "gateway:9142"
    USERLOG_MACHINE_AUTH_API_KEY                           = random_password.machine_auth_api_key.result
    USERLOG_JWT_SECRET                                     = random_password.jwt_secret.result
    # STORAGE_PUBLICLINK_LOG_COLOR                           = "false"
    # STORAGE_PUBLICLINK_LOG_LEVEL                           = "info"
    # STORAGE_PUBLICLINK_LOG_PRETTY                          = "false"
    # STORAGE_PUBLICLINK_TRACING_ENABLED                     = "false"
    # STORAGE_PUBLICLINK_TRACING_TYPE                        = "jaeger"
    # STORAGE_PUBLICLINK_TRACING_ENDPOINT                    = ""
    # STORAGE_PUBLICLINK_TRACING_COLLECTOR                   = ""
    # STORAGE_PUBLICLINK_DEBUG_PPROF                         = "false"
    # STORAGE_PUBLICLINK_GRPC_ADDR                           = "0.0.0.0:9178"
    # STORAGE_PUBLICLINK_DEBUG_ADDR                          = "0.0.0.0:9179"
    # OCIS_REVA_GATEWAY                                      = "gateway:9142"
    STORAGE_PUBLICLINK_JWT_SECRET                          = random_password.jwt_secret.result
    # PROXY_LOG_COLOR                                        = "false"
    # PROXY_LOG_LEVEL                                        = "info"
    # PROXY_LOG_PRETTY                                       = "false"
    # PROXY_TRACING_ENABLED                                  = "false"
    # PROXY_TRACING_TYPE                                     = "jaeger"
    # PROXY_TRACING_ENDPOINT                                 = ""
    # PROXY_TRACING_COLLECTOR                                = ""
    # PROXY_DEBUG_PPROF                                      = "false"
    # PROXY_HTTP_ADDR                                        = "0.0.0.0:9200"
    # PROXY_DEBUG_ADDR                                       = "0.0.0.0:9205"
    PROXY_ENABLE_BASIC_AUTH                                = "false"
    PROXY_OIDC_ISSUER                                      = "https://idp.${var.server_base_domain}/realms/${var.server_base_domain}"
    PROXY_OIDC_REWRITE_WELLKNOWN                           = "true"
    PROXY_USER_OIDC_CLAIM                                  = "preferred_username"
    PROXY_USER_CS3_CLAIM                                   = "userid"
    PROXY_OIDC_ACCESS_TOKEN_VERIFY_METHOD                  = "jwt"
    PROXY_OIDC_SKIP_CLIENT_ID_CHECK                        = "true"
    PROXY_TLS                                              = "false"
    # OCIS_REVA_GATEWAY                                      = "gateway:9142"
    PROXY_OIDC_INSECURE                                    = "false"
    PROXY_OIDC_USERINFO_CACHE_STORE                        = "noop"
    PROXY_JWT_SECRET                                       = random_password.jwt_secret.result
    PROXY_MACHINE_AUTH_API_KEY                             = random_password.machine_auth_api_key.result
    # EVENTHISTORY_LOG_COLOR                                 = "false"
    # EVENTHISTORY_LOG_LEVEL                                 = "info"
    # EVENTHISTORY_LOG_PRETTY                                = "false"
    # EVENTHISTORY_DEBUG_PPROF                               = "false"
    # EVENTHISTORY_GRPC_ADDR                                 = "0.0.0.0=8080"
    # EVENTHISTORY_DEBUG_ADDR                                = "0.0.0.0:9270"
    # EVENTHISTORY_STORE                                     = "nats-js"
    # EVENTHISTORY_STORE_NODES                               = "nats:9233"
    # EVENTHISTORY_EVENTS_ENDPOINT                           = "nats:9233"
    # STORAGE_USERS_LOG_COLOR                                = "false"
    # STORAGE_USERS_LOG_LEVEL                                = "info"
    # STORAGE_USERS_LOG_PRETTY                               = "false"
    # STORAGE_USERS_TRACING_ENABLED                          = "false"
    # STORAGE_USERS_TRACING_TYPE                             = "jaeger"
    # STORAGE_USERS_TRACING_ENDPOINT                         = ""
    # STORAGE_USERS_TRACING_COLLECTOR                        = ""
    # STORAGE_USERS_DEBUG_PPROF                              = "false"
    # STORAGE_USERS_GRPC_ADDR                                = "0.0.0.0:9157"
    # STORAGE_USERS_DEBUG_ADDR                               = "0.0.0.0:9159"
    # STORAGE_USERS_HTTP_ADDR                                = "0.0.0.0:9158"
    # STORAGE_USERS_DATA_SERVER_URL                          = "http://storageusers:9158/data"
    # STORAGE_USERS_PERMISSION_ENDPOINT                      = "settings:9191"
    # STORAGE_USERS_DRIVER                                   = "ocis"
    # STORAGE_USERS_OCIS_METADATA_BACKEND                    = "messagepack"
    # STORAGE_USERS_EVENTS_ENDPOINT                          = "nats:9233"
    # STORAGE_USERS_UPLOAD_EXPIRATION                        = "86400"
    # STORAGE_USERS_PURGE_TRASH_BIN_PERSONAL_DELETE_BEFORE   = "30d"
    # STORAGE_USERS_PURGE_TRASH_BIN_PROJECT_DELETE_BEFORE    = "30d"
    # STORAGE_USERS_PURGE_TRASH_BIN_USER_ID                  = ""
    OCIS_MACHINE_AUTH_API_KEY                              = random_password.machine_auth_api_key.result
    # OCIS_REVA_GATEWAY                                      = "gateway:9142"
    # STORAGE_USERS_FILEMETADATA_CACHE_STORE                 = "noop"
    # STORAGE_USERS_ID_CACHE_STORE                           = "noop"
    # STORAGE_USERS_STAT_CACHE_STORE                         = "noop"
    STORAGE_USERS_MOUNT_ID                                 = "3081f183-2e58-4f6f-8bb1-900a4152058a" # *****
    STORAGE_USERS_JWT_SECRET                               = random_password.jwt_secret.result
    OCIS_TRANSFER_SECRET                                   = random_password.transfer_secret.result
    # OCIS_ASYNC_UPLOADS                                     = "true"
    # STORAGE_USERS_DATA_GATEWAY_URL                         = "http://frontend:9140/data/"
    # SEARCH_LOG_COLOR                                       = "false"
    # SEARCH_LOG_LEVEL                                       = "info"
    # SEARCH_LOG_PRETTY                                      = "false"
    # SEARCH_DEBUG_PPROF                                     = "false"
    # SEARCH_GRPC_ADDR                                       = "0.0.0.0:9220"
    # SEARCH_DEBUG_ADDR                                      = "0.0.0.0:9224"
    # OCIS_REVA_GATEWAY                                      = "gateway:9142"
    # SEARCH_EVENTS_ENDPOINT                                 = "nats:9233"
    # SEARCH_EXTRACTOR_TYPE                                  = "basic"
    # SEARCH_EXTRACTOR_CS3SOURCE_INSECURE                    = "false"
    SEARCH_MACHINE_AUTH_API_KEY                            = random_password.machine_auth_api_key.result
    # OCIS_ASYNC_UPLOADS                                     = "true"
    # THUMBNAILS_LOG_COLOR                                   = "false"
    # THUMBNAILS_LOG_LEVEL                                   = "info"
    # THUMBNAILS_LOG_PRETTY                                  = "false"
    # THUMBNAILS_TRACING_ENABLED                             = "false"
    # THUMBNAILS_TRACING_TYPE                                = "jaeger"
    # THUMBNAILS_TRACING_ENDPOINT                            = ""
    # THUMBNAILS_TRACING_COLLECTOR                           = ""
    # THUMBNAILS_DEBUG_PPROF                                 = "false"
    # THUMBNAILS_GRPC_ADDR                                   = "0.0.0.0:9185"
    # THUMBNAILS_HTTP_ADDR                                   = "0.0.0.0:9186"
    # THUMBNAILS_DEBUG_ADDR                                  = "0.0.0.0:9189"
    # THUMBNAILS_DATA_ENDPOINT                               = "http://thumbnails:9186/thumbnails/data"
    # THUMBNAILS_WEBDAVSOURCE_INSECURE                       = "false"
    # THUMBNAILS_CS3SOURCE_INSECURE                          = "false"
    # OCIS_REVA_GATEWAY                                      = "gateway:9142"
    THUMBNAILS_TRANSFER_TOKEN                              = random_password.thumbnails_transfer_secret.result
    # OCDAV_LOG_COLOR                                        = "false"
    # OCDAV_LOG_LEVEL                                        = "info"
    # OCDAV_LOG_PRETTY                                       = "false"
    # OCDAV_TRACING_ENABLED                                  = "false"
    # OCDAV_TRACING_TYPE                                     = "jaeger"
    # OCDAV_TRACING_ENDPOINT                                 = ""
    # OCDAV_TRACING_COLLECTOR                                = ""
    # OCDAV_DEBUG_PPROF                                      = "false"
    # OCDAV_HTTP_ADDR                                        = "0.0.0.0=8080"
    # OCDAV_DEBUG_ADDR                                       = "0.0.0.0:9163"
    OCDAV_PUBLIC_URL                                       = "https://ocis.${var.server_base_domain}"
    OCIS_EDITION                                           = "Community"
    # OCIS_REVA_GATEWAY                                      = "gateway:9142"
    # OCDAV_INSECURE                                         = "false"
    OCDAV_JWT_SECRET                                       = random_password.jwt_secret.result
    OCDAV_MACHINE_AUTH_API_KEY                             = random_password.machine_auth_api_key.result
    # GRAPH_LOG_COLOR                                        = "false"
    # GRAPH_LOG_LEVEL                                        = "info"
    # GRAPH_LOG_PRETTY                                       = "false"
    # GRAPH_TRACING_ENABLED                                  = "false"
    # GRAPH_TRACING_TYPE                                     = "jaeger"
    # GRAPH_TRACING_ENDPOINT                                 = ""
    # GRAPH_TRACING_COLLECTOR                                = ""
    # GRAPH_DEBUG_PPROF                                      = "false"
    # GRAPH_HTTP_ADDR                                        = "0.0.0.0:9120"
    # GRAPH_DEBUG_ADDR                                       = "0.0.0.0:9124"
    GRAPH_SPACES_WEBDAV_BASE                               = "https://ocis.${var.server_base_domain}"
    GRAPH_LDAP_URI                                         = "ldaps://idm.${var.server_base_domain}"
    GRAPH_LDAP_BIND_DN                                     = "uid=${data.terraform_remote_state.openldap.outputs.admin_username},ou=people,dc=idm,dc=${var.server_base_domain}"
    GRAPH_LDAP_BIND_PASSWORD                               = data.terraform_remote_state.openldap.outputs.admin_password
    GRAPH_LDAP_SERVER_WRITE_ENABLED                        = "false"
    GRAPH_LDAP_CACERT                                      = ""
    GRAPH_LDAP_INSECURE                                    = "false"
    GRAPH_LDAP_SERVER_UUID                                 = "true"
    GRAPH_LDAP_SERVER_USE_PASSWORD_MODIFY_EXOP             = "false"
    GRAPH_LDAP_REFINT_ENABLED                              = "false"
    GRAPH_LDAP_USER_BASE_DN                                = "ou=people,dc=idm,dc=${var.server_base_domain}"
    GRAPH_LDAP_GROUP_BASE_DN                               = "ou=groups,dc=idm,dc=${var.server_base_domain}"
    GRAPH_LDAP_GROUP_CREATE_BASE_DN                        = "ou=groups,dc=idm,dc=${var.server_base_domain}"
    GRAPH_LDAP_USER_SCOPE                                  = "sub"
    GRAPH_LDAP_GROUP_SEARCH_SCOPE                          = "sub"
    GRAPH_LDAP_USER_FILTER                                 = ""
    GRAPH_LDAP_GROUP_FILTER                                = ""
    GRAPH_LDAP_USER_OBJECTCLASS                            = "inetOrgPerson"
    GRAPH_LDAP_GROUP_OBJECTCLASS                           = "groupOfNames"
    GRAPH_LDAP_USER_UID_ATTRIBUTE                          = "uid"
    GRAPH_LDAP_GROUP_ID_ATTRIBUTE                          = "cn"
    GRAPH_LDAP_USER_EMAIL_ATTRIBUTE                        = "mail"
    GRAPH_LDAP_USER_DISPLAYNAME_ATTRIBUTE                  = "displayname"
    GRAPH_LDAP_USER_NAME_ATTRIBUTE                         = "uid"
    GRAPH_LDAP_USER_TYPE_ATTRIBUTE                         = "ownCloudUserType"
    GRAPH_LDAP_GROUP_NAME_ATTRIBUTE                        = "cn"
    GRAPH_LDAP_USER_SCHEMA_ID_IS_OCTETSTRING               = "false"
    GRAPH_LDAP_GROUP_SCHEMA_ID_IS_OCTETSTRING              = "false"
    GRAPH_USER_ENABLED_ATTRIBUTE                           = "ownCloudUserEnabled"
    GRAPH_DISABLE_USER_MECHANISM                           = "group"
    GRAPH_DISABLED_USERS_GROUP_DN                          = "cn=app_disabled,ou=groups,dc=idm,dc=${var.server_base_domain}"
    # GRAPH_CACHE_STORE                                      = "noop"
    # OCIS_REVA_GATEWAY                                      = "gateway:9142"
    # GRAPH_EVENTS_ENDPOINT                                  = "nats:9233"
    GRAPH_APPLICATION_ID                                   = "1a194158-7bfe-4375-a00f-4db4a903afa4" # *****
    GRAPH_JWT_SECRET                                       = random_password.jwt_secret.result
    USERLOG_MACHINE_AUTH_API_KEY                           = random_password.machine_auth_api_key.result
    # STORE_LOG_COLOR                                        = "false"
    # STORE_LOG_LEVEL                                        = "info"
    # STORE_LOG_PRETTY                                       = "false"
    # STORE_TRACING_ENABLED                                  = "false"
    # STORE_TRACING_TYPE                                     = "jaeger"
    # STORE_TRACING_ENDPOINT                                 = ""
    # STORE_TRACING_COLLECTOR                                = ""
    # STORE_DEBUG_PPROF                                      = "false"
    # STORE_GRPC_ADDR                                        = "0.0.0.0:9460"
    # STORE_DEBUG_ADDR                                       = "0.0.0.0:9464"
    # NOTIFICATIONS_LOG_COLOR                                = "false"
    # NOTIFICATIONS_LOG_LEVEL                                = "info"
    # NOTIFICATIONS_LOG_PRETTY                               = "false"
    # NOTIFICATIONS_DEBUG_PPROF                              = "false"
    # NOTIFICATIONS_DEBUG_ADDR                               = "0.0.0.0:9174"
    NOTIFICATIONS_SMTP_HOST                                = "testy"
    NOTIFICATIONS_SMTP_PORT                                = "testy"
    NOTIFICATIONS_SMTP_SENDER                              = "OCIS <noreply@${var.server_base_domain}>"
    NOTIFICATIONS_SMTP_AUTHENTICATION                      = "login"
    NOTIFICATIONS_SMTP_ENCRYPTION                          = "tls"
    NOTIFICATIONS_SMTP_USERNAME                            = var.smtp_username
    NOTIFICATIONS_SMTP_PASSWORD                            = var.smtp_password
    OCIS_URL                                               = "https://ocis.${var.server_base_domain}"
    NOTIFICATIONS_WEB_UI_URL                               = "https://ocis.${var.server_base_domain}"
    # OCIS_REVA_GATEWAY                                      = "gateway:9142"
    # NOTIFICATIONS_EVENTS_ENDPOINT                          = "nats:9233"
    NOTIFICATIONS_MACHINE_AUTH_API_KEY                     = random_password.machine_auth_api_key.result

    OCIS_JWT_SECRET = random_password.jwt_secret.result
    OCIS_EXCLUDE_RUN_SERVICES = "idm,idp,auth-basic"
    PROXY_ROLE_ASSIGNMENT_DRIVER      = "oidc"
    PROXY_ROLE_ASSIGNMENT_OIDC_CLAIM = "roles"
  }
}

resource "kubernetes_deployment" "ocis" {
  metadata {
    name      = "ocis"
    namespace = kubernetes_namespace.ocis.metadata[0].name
  }

  spec {
    replicas = 1

    selector {
      match_labels = {
        app = "ocis"
      }
    }

    template {
      metadata {
        labels = {
          app = "ocis"
        }
      }

      spec {
        container {
          image = "owncloud/ocis:3.0.0"
          name  = "ocis"

          command = ["sh", "-c", "ocis server"]

          env_from {
            secret_ref {
              name = kubernetes_secret.ocis_config.metadata[0].name
            }
          }

          #   volume_mount {
          #     mount_path = "/var/lib/ocis/"
          #     name       = "ocis-data"
          #   }
        }
      }
    }
  }

  timeouts {
    create = "1m"
    update = "1m"
    delete = "1m"
  }

  lifecycle {
    replace_triggered_by = [
      kubernetes_secret.ocis_config
    ]
  }
}
