name: 'Terraform Deploy'
description: 'Deploy Terraform configuration'
inputs:
  terraform-dir:
    required: true
    type: string
  resource-name:
    required: false
    type: string
    default: ''
  extra-variable:
    required: false
    type: string
    default: ''

runs:
  using: "composite"

  steps:
    - name: "Add cluster CA certificate"
      shell: bash
      run: "echo $CLUSTER_CA_CERT_DATA > cluster.cert.pem && sudo mkdir /usr/local/share/ca-certificates/extra && sudo cp cluster.cert.pem /usr/local/share/ca-certificates/extra/cluster.cert.crt && sudo update-ca-certificates"
    - name: "Setup node"
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: "Terraform setup"
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6
    - name: "Generate kubeconfig"
      working-directory: ${{ inputs.terraform-dir }}/..
      shell: bash
      run: |
        ./cluster-config-write.sh
        mkdir ~/.kube
        cp cluster.yml ~/.kube/config
    - name: "Terraform format check"
      working-directory: ${{ inputs.terraform-dir }}
      shell: bash
      run: "terraform fmt -check"
    - name: "Terraform init"
      working-directory: ${{ inputs.terraform-dir }}
      shell: bash
      run: "terraform init"
    - name: "Terraform apply all resources"
      working-directory: ${{ inputs.terraform-dir }}
      shell: bash
      if: "${{ ('' == inputs.resource-name) && ('' == inputs.extra-variable) }}"
      run: "terraform apply -auto-approve -input=false"
    - name: "Terraform apply specific resource"
      working-directory: ${{ inputs.terraform-dir }}
      shell: bash
      if: "${{ '' != inputs.resource-name }}"
      run: "terraform apply -auto-approve -input=false -target=${{ inputs.resource-name }}"
    - name: "Terraform apply extra variable"
      working-directory: ${{ inputs.terraform-dir }}
      shell: bash
      if: "${{ '' != inputs.extra-variable }}"
      run: "terraform apply -auto-approve -input=false -var=${{ inputs.extra-variable }}"