apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kube-prometheus-stack-k8s.rules.container-memory-rss
  namespace: default
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/version: 88.1.2
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-88.1.2
    release: kube-prometheus-stack
    heritage: Helm
spec:
  groups:
  - name: k8s.rules.container_memory_rss
    rules:
    - expr: "container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", image!=\"\"}\n* on (cluster, namespace, pod) group_left(node) topk by (cluster, namespace, pod) (1,\n  max by (cluster, namespace, pod, node) (kube_pod_info{node!=\"\"})\n)"
      record: node_namespace_pod_container:container_memory_rss
