apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kube-prometheus-stack-k8s.rules.container-cpu-usage-seconds-tot
  namespace: default
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/version: 88.1.2
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-88.1.2
    release: kube-prometheus-stack
    heritage: Helm
spec:
  groups:
  - name: k8s.rules.container_cpu_usage_seconds_total
    rules:
    - expr: "sum by (cluster, namespace, pod, container) (\n  rate(container_cpu_usage_seconds_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", image!=\"\"}[5m])\n) * on (cluster, namespace, pod) group_left(node) topk by (cluster, namespace, pod) (\n  1, max by (cluster, namespace, pod, node) (kube_pod_info{node!=\"\"})\n)"
      record: node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m
    - expr: "sum by (cluster, namespace, pod, container) (\n  irate(container_cpu_usage_seconds_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", image!=\"\"}[5m])\n) * on (cluster, namespace, pod) group_left(node) topk by (cluster, namespace, pod) (\n  1, max by (cluster, namespace, pod, node) (kube_pod_info{node!=\"\"})\n)"
      record: node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate
