on:
  workflow_call:
    inputs:
      runner-type:
        required: true
        type: string
        default: self-hosted

jobs:
  deploy-kubernetes-terraform:
    runs-on: ${{ inputs.runner-type }}

    steps:
      - name: "Repo checkout"
        uses: actions/checkout@v3
      - name: "Setup node"
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: "Generate kubeconfig"
        working-directory: ./terraform
        run: "./cluster-config-write.sh"
      - name: "Add cluster CA certificate"
        run: "echo $CLUSTER_CA_CERT_DATA > cluster.cert.pem && sudo mkdir /usr/local/share/ca-certificates/extra && sudo cp cluster.cert.pem /usr/local/share/ca-certificates/extra/cluster.cert.crt && sudo update-ca-certificates"
      - name: "Setup kubectl"
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.25.3'
      - name: "Create terraform-state namespace"
        working-directory: ./terraform
        run: "kubectl --kubeconfig ./cluster.yml apply -f ./terraform-state-namespace.yml"
