on:
  workflow_dispatch:
    inputs:
      do-hibernate:
        description: 'True to hibernate databases. False to restart.'
        required: true
        default: true
        type: boolean
  workflow_call:
    inputs:
      do-hibernate:
        required: true
        type: boolean
    outputs:
      attempted:
        description: "True if at least one hibernate/restart matrix leg actually executed"
        value: ${{ jobs.report-hibernation-status.outputs.attempted }}

env:
  CLIENT_CERT_DATA: ${{ secrets.KUBE_CLIENT_CERT_DATA }}
  CLIENT_KEY_DATA: ${{ secrets.KUBE_CLIENT_KEY_DATA }}
  CLUSTER_CA_CERT_DATA: ${{ secrets.KUBE_CLUSTER_CA_CERT_DATA }}
  SERVER_IP_ADDRESS: ${{ secrets.K3S_IP_ADDRESS }}
  SERVER_KUBE_PORT: ${{ vars.SERVER_KUBE_PORT }}

jobs:
  get-postgres-databases:
    runs-on: self-hosted

    outputs:
      databases: ${{ steps.get-databases.outputs.databases}}

    steps:
      - name: "Repo checkout"
        uses: actions/checkout@v7
      - name: "Add cluster CA certificate"
        run: |
          echo "$CLUSTER_CA_CERT_DATA" > cluster.cert.pem
          sudo mkdir /usr/local/share/ca-certificates/extra
          sudo cp cluster.cert.pem /usr/local/share/ca-certificates/extra/cluster.cert.crt
          sudo update-ca-certificates
      - name: "Generate and install kubeconfig"
        working-directory: ./terraform
        run: |
          ./cluster-config-write.sh
          mkdir ~/.kube
          cp cluster.yml ~/.kube/config
      - name: "Setup kubectl"
        uses: azure/setup-kubectl@v5
        with:
          version: 'v1.33.6'
      - name: "Get Databases"
        id: "get-databases"
        run: |
          kubectl get clusters.postgresql.cnpg.io -A -o yaml > clusters.yml
          yq '.items[].metadata | pick(["name", "namespace"])' clusters.yml -o json -I 0 > dbs.json
          sed -i '{:q;N;s/\n/, /g;t q}' dbs.json
          sed -i 's#^#[#' dbs.json
          sed -i 's#$#]#' dbs.json
          truncate -s -1 dbs.json
          echo "databases=$(cat dbs.json)" >> "$GITHUB_OUTPUT"

  get-clickhouse-databases:
    runs-on: self-hosted

    outputs:
      databases: ${{ steps.get-databases.outputs.databases}}

    steps:
      - name: "Repo checkout"
        uses: actions/checkout@v7
      - name: "Add cluster CA certificate"
        run: |
          echo "$CLUSTER_CA_CERT_DATA" > cluster.cert.pem
          sudo mkdir /usr/local/share/ca-certificates/extra
          sudo cp cluster.cert.pem /usr/local/share/ca-certificates/extra/cluster.cert.crt
          sudo update-ca-certificates
      - name: "Generate and install kubeconfig"
        working-directory: ./terraform
        run: |
          ./cluster-config-write.sh
          mkdir ~/.kube
          cp cluster.yml ~/.kube/config
      - name: "Setup kubectl"
        uses: azure/setup-kubectl@v5
        with:
          version: 'v1.33.6'
      - name: "Get Databases"
        id: "get-databases"
        run: |
          kubectl get clickhouseinstallations -A -o yaml > clusters.yml
          yq '.items[] | {"name": .metadata.name, "namespace": .metadata.namespace, "replicas": (.spec.configuration.clusters[0].layout.replicasCount // 1)}' clusters.yml -o json -I 0 > dbs.json
          sed -i '{:q;N;s/\n/, /g;t q}' dbs.json
          sed -i 's#^#[#' dbs.json
          sed -i 's#$#]#' dbs.json
          truncate -s -1 dbs.json
          echo "databases=$(cat dbs.json)" >> "$GITHUB_OUTPUT"

  get-clickhouse-keeper-databases:
    runs-on: self-hosted

    outputs:
      databases: ${{ steps.get-databases.outputs.databases}}

    steps:
      - name: "Repo checkout"
        uses: actions/checkout@v7
      - name: "Add cluster CA certificate"
        run: |
          echo "$CLUSTER_CA_CERT_DATA" > cluster.cert.pem
          sudo mkdir /usr/local/share/ca-certificates/extra
          sudo cp cluster.cert.pem /usr/local/share/ca-certificates/extra/cluster.cert.crt
          sudo update-ca-certificates
      - name: "Generate and install kubeconfig"
        working-directory: ./terraform
        run: |
          ./cluster-config-write.sh
          mkdir ~/.kube
          cp cluster.yml ~/.kube/config
      - name: "Setup kubectl"
        uses: azure/setup-kubectl@v5
        with:
          version: 'v1.33.6'
      - name: "Get Databases"
        id: "get-databases"
        run: |
          kubectl get clickhousekeeperinstallations -A -o yaml > clusters.yml
          yq '.items[] | {"name": .metadata.name, "namespace": .metadata.namespace}' clusters.yml -o json -I 0 > dbs.json
          sed -i '{:q;N;s/\n/, /g;t q}' dbs.json
          sed -i 's#^#[#' dbs.json
          sed -i 's#$#]#' dbs.json
          truncate -s -1 dbs.json
          echo "databases=$(cat dbs.json)" >> "$GITHUB_OUTPUT"

  get-mariadb-databases:
    runs-on: self-hosted

    outputs:
      databases: ${{ steps.get-databases.outputs.databases}}

    steps:
      - name: "Repo checkout"
        uses: actions/checkout@v7
      - name: "Add cluster CA certificate"
        run: |
          echo "$CLUSTER_CA_CERT_DATA" > cluster.cert.pem
          sudo mkdir /usr/local/share/ca-certificates/extra
          sudo cp cluster.cert.pem /usr/local/share/ca-certificates/extra/cluster.cert.crt
          sudo update-ca-certificates
      - name: "Generate and install kubeconfig"
        working-directory: ./terraform
        run: |
          ./cluster-config-write.sh
          mkdir ~/.kube
          cp cluster.yml ~/.kube/config
      - name: "Setup kubectl"
        uses: azure/setup-kubectl@v5
        with:
          version: 'v1.33.6'
      - name: "Get Databases"
        id: "get-databases"
        run: |
          kubectl get mariadbs.k8s.mariadb.com -A -o yaml > clusters.yml
          yq '.items[].metadata | pick(["name", "namespace"])' clusters.yml -o json -I 0 > dbs.json
          sed -i '{:q;N;s/\n/, /g;t q}' dbs.json
          sed -i 's#^#[#' dbs.json
          sed -i 's#$#]#' dbs.json
          truncate -s -1 dbs.json
          echo "databases=$(cat dbs.json)" >> "$GITHUB_OUTPUT"

  hibernate-postgres-databases:
    needs: [
      get-postgres-databases,
    ]
    runs-on: self-hosted
    if: ${{ needs.get-postgres-databases.outputs.databases != '' }}

    strategy:
      fail-fast: false
      matrix:
        database: ${{ fromJson(needs.get-postgres-databases.outputs.databases) }}

    steps:
      - name: "Repo checkout"
        uses: actions/checkout@v7
      - name: "Add cluster CA certificate"
        run: |
          echo "$CLUSTER_CA_CERT_DATA" > cluster.cert.pem
          sudo mkdir /usr/local/share/ca-certificates/extra
          sudo cp cluster.cert.pem /usr/local/share/ca-certificates/extra/cluster.cert.crt
          sudo update-ca-certificates
      - name: "Generate and install kubeconfig"
        working-directory: ./terraform
        run: |
          ./cluster-config-write.sh
          mkdir ~/.kube
          cp cluster.yml ~/.kube/config
      - name: "Setup kubectl"
        uses: azure/setup-kubectl@v5
        with:
          version: 'v1.33.6'
      - name: "Hibernate / restart DB"
        env:
          HIBERNATE_CHOICE: ${{ inputs.do-hibernate && 'on' || 'off' }}
        run: "kubectl -n ${{ matrix.database.namespace }} annotate clusters.postgresql.cnpg.io ${{ matrix.database.name }} --overwrite cnpg.io/hibernation=${{ env.HIBERNATE_CHOICE }}"
      - name: "Wait for hibernate"
        if: ${{ inputs.do-hibernate }}
        run: kubectl -n ${{ matrix.database.namespace }} wait clusters.postgresql.cnpg.io ${{ matrix.database.name }} --timeout 30m --for "jsonpath={.status.conditions[?(.type==\"cnpg.io/hibernation\")].status}=True"
      - name: "Wait for restart"
        if: ${{ !inputs.do-hibernate }}
        run: kubectl -n ${{ matrix.database.namespace }} wait clusters.postgresql.cnpg.io ${{ matrix.database.name }} --timeout 30m --for "jsonpath={.status.readyInstances}=$(kubectl -n ${{ matrix.database.namespace }} get clusters.postgresql.cnpg.io ${{ matrix.database.name }} -o "jsonpath={.status.instances}")"

  hibernate-clickhouse-databases:
    needs: [
      get-clickhouse-databases,
    ]
    runs-on: self-hosted
    if: ${{ needs.get-clickhouse-databases.outputs.databases != '' }}

    strategy:
      fail-fast: false
      matrix:
        clickhouse: ${{ fromJson(needs.get-clickhouse-databases.outputs.databases) }}

    steps:
      - name: "Repo checkout"
        uses: actions/checkout@v7
      - name: "Add cluster CA certificate"
        run: |
          echo "$CLUSTER_CA_CERT_DATA" > cluster.cert.pem
          sudo mkdir /usr/local/share/ca-certificates/extra
          sudo cp cluster.cert.pem /usr/local/share/ca-certificates/extra/cluster.cert.crt
          sudo update-ca-certificates
      - name: "Generate and install kubeconfig"
        working-directory: ./terraform
        run: |
          ./cluster-config-write.sh
          mkdir ~/.kube
          cp cluster.yml ~/.kube/config
      - name: "Setup kubectl"
        uses: azure/setup-kubectl@v5
        with:
          version: 'v1.33.6'
      - name: "Hibernate / restart ClickHouse"
        env:
          STOP_VALUE: ${{ inputs.do-hibernate && '1' || '0' }}
        run: kubectl -n ${{ matrix.clickhouse.namespace }} patch clickhouseinstallation ${{ matrix.clickhouse.name }} --type=merge -p '{"spec":{"stop":"${{ env.STOP_VALUE }}"}}'
      - name: "Wait for scale down"
        if: ${{ inputs.do-hibernate }}
        run: kubectl -n ${{ matrix.clickhouse.namespace }} wait clickhouseinstallation ${{ matrix.clickhouse.name }} --timeout 30m --for "jsonpath={.status.status}=Completed"
      - name: "Wait for scale up"
        if: ${{ !inputs.do-hibernate }}
        run: kubectl -n ${{ matrix.clickhouse.namespace }} wait clickhouseinstallation ${{ matrix.clickhouse.name }} --timeout 30m --for "jsonpath={.status.status}=Completed"

  hibernate-clickhouse-keeper-databases:
    needs: [
      get-clickhouse-keeper-databases,
    ]
    runs-on: self-hosted
    if: ${{ needs.get-clickhouse-keeper-databases.outputs.databases != '' }}

    strategy:
      fail-fast: false
      matrix:
        database: ${{ fromJson(needs.get-clickhouse-keeper-databases.outputs.databases) }}

    steps:
      - name: "Repo checkout"
        uses: actions/checkout@v7
      - name: "Add cluster CA certificate"
        run: |
          echo "$CLUSTER_CA_CERT_DATA" > cluster.cert.pem
          sudo mkdir /usr/local/share/ca-certificates/extra
          sudo cp cluster.cert.pem /usr/local/share/ca-certificates/extra/cluster.cert.crt
          sudo update-ca-certificates
      - name: "Generate and install kubeconfig"
        working-directory: ./terraform
        run: |
          ./cluster-config-write.sh
          mkdir ~/.kube
          cp cluster.yml ~/.kube/config
      - name: "Setup kubectl"
        uses: azure/setup-kubectl@v5
        with:
          version: 'v1.33.6'
      - name: "Hibernate / restart Keeper"
        env:
          STOP_VALUE: ${{ inputs.do-hibernate && '1' || '0' }}
        run: kubectl -n ${{ matrix.database.namespace }} patch clickhousekeeperinstallation ${{ matrix.database.name }} --type=merge -p '{"spec":{"stop":"${{ env.STOP_VALUE }}"}}'
      - name: "Wait for hibernate"
        if: ${{ inputs.do-hibernate }}
        run: kubectl -n ${{ matrix.database.namespace }} wait clickhousekeeperinstallation ${{ matrix.database.name }} --timeout 30m --for "jsonpath={.status.status}=Completed"
      - name: "Wait for restart"
        if: ${{ !inputs.do-hibernate }}
        run: kubectl -n ${{ matrix.database.namespace }} wait clickhousekeeperinstallation ${{ matrix.database.name }} --timeout 30m --for "jsonpath={.status.status}=Completed"

  hibernate-mariadb-databases:
    needs: [
      get-mariadb-databases,
    ]
    runs-on: self-hosted
    if: ${{ needs.get-mariadb-databases.outputs.databases != '' }}

    strategy:
      fail-fast: false
      matrix:
        database: ${{ fromJson(needs.get-mariadb-databases.outputs.databases) }}

    steps:
      - name: "Repo checkout"
        uses: actions/checkout@v7
      - name: "Add cluster CA certificate"
        run: |
          echo "$CLUSTER_CA_CERT_DATA" > cluster.cert.pem
          sudo mkdir /usr/local/share/ca-certificates/extra
          sudo cp cluster.cert.pem /usr/local/share/ca-certificates/extra/cluster.cert.crt
          sudo update-ca-certificates
      - name: "Generate and install kubeconfig"
        working-directory: ./terraform
        run: |
          ./cluster-config-write.sh
          mkdir ~/.kube
          cp cluster.yml ~/.kube/config
      - name: "Setup kubectl"
        uses: azure/setup-kubectl@v5
        with:
          version: 'v1.33.6'
      - name: "Hibernate DB"
        if: ${{ inputs.do-hibernate }}
        run: |
          kubectl -n ${{ matrix.database.namespace }} patch mariadbs.k8s.mariadb.com ${{ matrix.database.name }} --type=merge -p '{"spec":{"suspend":true}}'
          kubectl -n ${{ matrix.database.namespace }} scale statefulset ${{ matrix.database.name }} --replicas=0
      - name: "Wait for hibernate"
        if: ${{ inputs.do-hibernate }}
        run: kubectl -n ${{ matrix.database.namespace }} wait statefulset ${{ matrix.database.name }} --timeout 30m --for "jsonpath={.status.replicas}=0"
      - name: "Restart DB"
        if: ${{ !inputs.do-hibernate }}
        run: kubectl -n ${{ matrix.database.namespace }} patch mariadbs.k8s.mariadb.com ${{ matrix.database.name }} --type=merge -p '{"spec":{"suspend":false}}'
      - name: "Wait for restart"
        if: ${{ !inputs.do-hibernate }}
        run: kubectl -n ${{ matrix.database.namespace }} wait mariadbs.k8s.mariadb.com ${{ matrix.database.name }} --timeout 30m --for "jsonpath={.status.conditions[?(.type==\"Ready\")].status}=True"

  # ***** other stateful apps hibernate

  hibernate-kafka:
    runs-on: self-hosted

    steps:
      - name: "Repo checkout"
        uses: actions/checkout@v7
      - name: "Add cluster CA certificate"
        run: |
          echo "$CLUSTER_CA_CERT_DATA" > cluster.cert.pem
          sudo mkdir /usr/local/share/ca-certificates/extra
          sudo cp cluster.cert.pem /usr/local/share/ca-certificates/extra/cluster.cert.crt
          sudo update-ca-certificates
      - name: "Generate and install kubeconfig"
        working-directory: ./terraform
        run: |
          ./cluster-config-write.sh
          mkdir ~/.kube
          cp cluster.yml ~/.kube/config
      - name: "Setup kubectl"
        uses: azure/setup-kubectl@v5
        with:
          version: 'v1.33.6'
      - name: "Hibernate Kafka"
        if: ${{ inputs.do-hibernate }}
        run: |
          kubectl -n kafka-operator scale deploy strimzi-cluster-operator --replicas=0
          kubectl -n kafka-operator wait pod -l strimzi.io/kind=cluster-operator --for=delete --timeout=5m
          kubectl delete pods -n posthog -l strimzi.io/cluster --timeout=10m
      - name: "Restart Kafka"
        if: ${{ !inputs.do-hibernate }}
        run: |
          kubectl -n kafka-operator scale deploy strimzi-cluster-operator --replicas=1
          kubectl -n kafka-operator wait deploy strimzi-cluster-operator --for=jsonpath='{.status.readyReplicas}=1' --timeout=5m
          kubectl -n posthog wait kafka kafka --timeout 30m --for "jsonpath={.status.conditions[?(@.type==\"Ready\")].status}=True"

  hibernate-opensearch:
    runs-on: self-hosted

    steps:
      - name: "Repo checkout"
        uses: actions/checkout@v7
      - name: "Add cluster CA certificate"
        run: |
          echo "$CLUSTER_CA_CERT_DATA" > cluster.cert.pem
          sudo mkdir /usr/local/share/ca-certificates/extra
          sudo cp cluster.cert.pem /usr/local/share/ca-certificates/extra/cluster.cert.crt
          sudo update-ca-certificates
      - name: "Generate and install kubeconfig"
        working-directory: ./terraform
        run: |
          ./cluster-config-write.sh
          mkdir ~/.kube
          cp cluster.yml ~/.kube/config
      - name: "Setup kubectl"
        uses: azure/setup-kubectl@v5
        with:
          version: 'v1.33.6'
      - name: "Hibernate OpenSearch"
        if: ${{ inputs.do-hibernate }}
        run: |
          kubectl -n opensearch-operator scale deploy opensearch-operator --replicas=0
          kubectl -n opensearch-operator wait pod -l app.kubernetes.io/name=opensearch-operator --for=delete --timeout=5m
          kubectl -n posthog delete pods -l opensearch.cluster.name --timeout=10m
      - name: "Restart OpenSearch"
        if: ${{ !inputs.do-hibernate }}
        run: |
          kubectl -n opensearch-operator scale deploy opensearch-operator --replicas=1
          kubectl -n opensearch-operator wait deploy opensearch-operator --for=jsonpath='{.status.readyReplicas}=1' --timeout=5m
          kubectl -n posthog wait pods -l opensearch.cluster.name --for=condition=Ready --timeout 30m

  report-hibernation-status:
    needs: [
      hibernate-postgres-databases,
      hibernate-clickhouse-databases,
      hibernate-clickhouse-keeper-databases,
      hibernate-mariadb-databases,
      hibernate-kafka,
      hibernate-opensearch,
    ]
    if: always() && !cancelled() && inputs.do-hibernate
    runs-on: ubuntu-latest
    outputs:
      attempted: ${{ (needs.hibernate-postgres-databases.result != 'skipped') || (needs.hibernate-clickhouse-databases.result != 'skipped') || (needs.hibernate-clickhouse-keeper-databases.result != 'skipped') || (needs.hibernate-mariadb-databases.result != 'skipped') || (needs.hibernate-kafka.result != 'skipped') || (needs.hibernate-opensearch.result != 'skipped') }}
    steps:
      - name: "Report status"
        run: echo "done"
