name: Deploy
on:
  workflow_dispatch:
    first-run:
      type: boolean
      description: Is this being run on a clean environment?

jobs:
  deploy-terraform-state-namespace:
    uses: ./.github/workflows/terraform-state-namespace-deploy.yml
    secrets: inherit

    with:
      runner-type: ${{ first-run && "ubuntu-latest" || "self-hosted" }}

  deploy-github-org-runner-1:
    needs: [
      deploy-terraform-state-namespace,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/github-org-runners-1
      runner-type: ${{ first-run && "ubuntu-latest" || "self-hosted" }}

  deploy-github-org-runner-2:
    needs: deploy-github-org-runner-1
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/github-org-runners-2
      runner-type: ${{ first-run && "ubuntu-latest" || "self-hosted" }}

  deploy-traefik:
    needs: [
      deploy-terraform-state-namespace,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/traefik
      runner-type: ${{ first-run && "ubuntu-latest" || "self-hosted" }}

  # deploy-velero:
  #   needs: [
  #     deploy-terraform-state-namespace,
  #   ]
  #   uses: ./.github/workflows/kubernetes-terraform-deploy.yml
  #   secrets: inherit

  #   with:
  #     terraform-dir: ./terraform/velero

  deploy-services:
    needs: [
      deploy-github-org-runner-2,
      deploy-traefik,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/services

  deploy-openldap:
    needs: [
      deploy-github-org-runner-2,
      deploy-traefik,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/openldap

  deploy-keycloak:
    needs: [
      deploy-github-org-runner-2,
      deploy-traefik,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/keycloak

  deploy-keycloak-config:
    needs: [
      deploy-openldap,
      deploy-keycloak,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/keycloak-config

  deploy-vaultwarden:
    needs: [
      deploy-openldap,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/vaultwarden

  deploy-ocis:
    needs: [
      deploy-keycloak-config,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/ocis
