name: Deploy
on:
  workflow_dispatch:
    inputs:
      use-github-runners:
        type: boolean
        description: Use Github Runners

env:
  RUNNER_TYPE: ${{ true == github.event.inputs.use-github-runners && 'test-val-1' || 'test-val-2' }}

jobs:
  deploy-terraform-state-namespace:
    uses: ./.github/workflows/terraform-state-namespace-deploy.yml
    secrets: inherit

    with:
      runner-type: ${{ true == github.event.inputs.use-github-runners && 'test-val-1' || 'test-val-2' }}

  deploy-github-org-runner-1:
    needs: [
      deploy-terraform-state-namespace,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/github-org-runners-1
      runner-type: $RUNNER_TYPE

  deploy-github-org-runner-2:
    needs: [
      deploy-github-org-runner-1,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/github-org-runners-2
      runner-type: $RUNNER_TYPE

  deploy-traefik:
    needs: [
      deploy-terraform-state-namespace,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/traefik
      runner-type: $RUNNER_TYPE

  # deploy-velero:
  #   needs: [
  #     deploy-terraform-state-namespace,
  #   ]
  #   uses: ./.github/workflows/kubernetes-terraform-deploy.yml
  #   secrets: inherit

  #   with:
  #     terraform-dir: ./terraform/velero

  deploy-services:
    needs: [
      deploy-github-org-runner-2,
      deploy-traefik,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/services

  deploy-openldap:
    needs: [
      deploy-github-org-runner-2,
      deploy-traefik,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/openldap

  deploy-keycloak:
    needs: [
      deploy-github-org-runner-2,
      deploy-traefik,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/keycloak

  deploy-keycloak-config:
    needs: [
      deploy-openldap,
      deploy-keycloak,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/keycloak-config

  deploy-vaultwarden:
    needs: [
      deploy-openldap,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/vaultwarden

  deploy-ocis:
    needs: [
      deploy-keycloak-config,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/ocis
