name: Deploy
on:
  workflow_dispatch:
    inputs:
      runner-type:
        description: 'Runners to use'
        required: true
        default: self-hosted
        type: choice
        options:
          - self-hosted
          - ubuntu-latest
  workflow_call:
    inputs:
      runner-type:
        required: false
        default: self-hosted
        type: string

jobs:
  deploy-tf-state-namespace:
    uses: ./.github/workflows/kubernetes-manifest-deploy.yml
    secrets: inherit

    with:
      manifest-file: ./terraform/tf-state-namespace.yml
      runner-type: ${{ github.event.inputs.runner-type }}

  deploy-github-org-runner:
    needs: [
      deploy-tf-state-namespace,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/github-org-runners
      runner-type: ${{ github.event.inputs.runner-type }}

  deploy-openebs:
    needs: [
      deploy-github-org-runner,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/openebs

  deploy-prometheus-operator:
    needs: [
      deploy-github-org-runner,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/prometheus-operator
      needs-kubectl: true
      needs-helm: true

  deploy-traefik:
    needs: [
      deploy-openebs,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/traefik

  deploy-cloudnative-pg:
    needs: [
      deploy-github-org-runner,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/cloudnative-pg

  deploy-velero:
    needs: [
      deploy-openebs,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/velero

  deploy-loki:
    needs: [
      deploy-openebs,
      deploy-prometheus-operator,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/loki

  deploy-openldap:
    needs: [
      deploy-traefik,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/openldap

  deploy-keycloak:
    needs: [
      deploy-traefik,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/keycloak

  deploy-harbor:
    needs: [
      deploy-traefik,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/harbor

  deploy-drawio:
    needs: [
      deploy-traefik,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/drawio

  deploy-traefik-config:
    needs: [
      deploy-traefik,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/traefik-config

  deploy-keycloak-config:
    needs: [
      deploy-openldap,
      deploy-keycloak,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/keycloak-config

  deploy-vaultwarden:
    needs: [
      deploy-openldap,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/vaultwarden

  deploy-ocis:
    needs: [
      deploy-keycloak-config,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/ocis

  deploy-oauth2-proxy:
    needs: [
      deploy-keycloak-config,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/oauth2-proxy

  deploy-outline:
    needs: [
      deploy-keycloak-config,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/outline

  deploy-penpot:
    needs: [
      deploy-keycloak-config,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/penpot

  deploy-services:
    needs: [
      deploy-oauth2-proxy,
      deploy-velero,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/services

  deploy-harbor-config:
    needs: [
      deploy-keycloak-config,
      deploy-harbor,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/harbor-config
