name: Deploy
on:
  workflow_dispatch:
  repository_dispatch:
    type: [deployment]
  push:
    branches:
      - 'trunk'

jobs:
  deploy-foundational-services:
    uses: ./.github/workflows/deploy-foundational-services.yml
    secrets: inherit

    with:
      runner-type: self-hosted

  deploy-services:
    needs: deploy-foundational-services

    uses: ./.github/workflows/kubernetes-terraform-deploy-self-hosted-runner.yml
    with:
      terraform-dir: ./terraform/apps/services
    secrets: inherit

  deploy-lldap:
    needs: deploy-foundational-services

    uses: ./.github/workflows/kubernetes-terraform-deploy-self-hosted-runner.yml
    with:
      terraform-dir: ./terraform/apps/lldap
    secrets: inherit

  deploy-openldap:
    needs: deploy-foundational-services

    uses: ./.github/workflows/kubernetes-terraform-deploy-self-hosted-runner.yml
    with:
      terraform-dir: ./terraform/apps/openldap
    secrets: inherit

  deploy-vaultwarden:
    needs: deploy-openldap

    uses: ./.github/workflows/kubernetes-terraform-deploy-self-hosted-runner.yml
    with:
      terraform-dir: ./terraform/apps/vaultwarden
    secrets: inherit

  deploy-keycloak:
    needs: deploy-foundational-services

    uses: ./.github/workflows/kubernetes-terraform-deploy-self-hosted-runner.yml
    with:
      terraform-dir: ./terraform/apps/keycloak
    secrets: inherit

  deploy-keycloak-config:
    needs: [deploy-openldap, deploy-keycloak]

    uses: ./.github/workflows/kubernetes-terraform-deploy-self-hosted-runner.yml
    with:
      terraform-dir: ./terraform/apps/keycloak-config
    secrets: inherit

  deploy-ocis:
    needs: deploy-keycloak-config

    uses: ./.github/workflows/kubernetes-terraform-deploy-self-hosted-runner.yml
    with:
      terraform-dir: ./terraform/apps/ocis
    secrets: inherit
