name: Deploy
on:
  workflow_dispatch:
    inputs:
      runner-type:
        description: 'Runners to use'
        required: true
        default: self-hosted
        type: choice
        options:
          - self-hosted
          - ubuntu-latest
  workflow_call:
    inputs:
      runner-type:
        required: false
        default: self-hosted
        type: string

jobs:
  deploy-tf-state-namespace:
    uses: ./.github/workflows/kubernetes-manifest-deploy.yml
    secrets: inherit

    with:
      manifest-file: ./terraform/tf-state-namespace.yml
      runner-type: ${{ github.event.inputs.runner-type }}

  deploy-github-org-runner:
    needs: [
      deploy-tf-state-namespace,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/github-org-runners
      runner-type: ${{ github.event.inputs.runner-type }}

  deploy-openebs:
    needs: [
      deploy-github-org-runner,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/openebs

  deploy-grafana-operator:
    needs: [
      deploy-github-org-runner,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/grafana-operator

  deploy-cert-manager:
    needs: [
      deploy-github-org-runner,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/openebs

  deploy-traefik:
    needs: [
      deploy-openebs,
      deploy-cert-manager,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/traefik

  deploy-cloudnative-pg:
    needs: [
      deploy-openebs,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/cloudnative-pg

  deploy-velero:
    needs: [
      deploy-openebs,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/velero

  deploy-crowdsec:
    needs: [
      deploy-traefik,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/crowdsec

  deploy-traefik-config:
    needs: [
      deploy-traefik,
      deploy-crowdsec,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/traefik-config

  deploy-openldap:
    needs: [
      deploy-traefik-config,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/openldap

  deploy-keycloak:
    needs: [
      deploy-cloudnative-pg,
      deploy-openldap,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/keycloak

  deploy-vaultwarden:
    needs: [
      deploy-cloudnative-pg,
      deploy-openldap,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/vaultwarden

  deploy-keycloak-dependants:
    needs: [
      deploy-keycloak,
      deploy-grafana-operator, # only needed for grafana
      deploy-velero, # only needed for services
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    strategy:
      fail-fast: false
      matrix:
        application: [
          drawio,
          whoami,
          grafana,
          ocis,
          outline,
          penpot,
          services,
        ]

    with:
      terraform-dir: ./terraform/${{ matrix.application }}
