name: Deploy
on:
  workflow_dispatch:
  repository_dispatch:
    type: [deployment]

jobs:
  deploy-foundational-services:
    uses: ./.github/workflows/deploy-foundational-services.yml
    secrets: inherit

  deploy-services:
    needs: deploy-foundational-services

    uses: ./.github/workflows/kubernetes-terraform-deploy-self-hosted-runner.yml
    with:
      terraform-dir: ./terraform/apps/services
    secrets: inherit

  deploy-ldap:
    needs: deploy-external-services

    uses: ./.github/workflows/kubernetes-terraform-deploy-self-hosted-runner.yml
    with:
      terraform-dir: ./terraform/apps/ldap
    secrets: inherit

  deploy-vaultwarden:
    needs: deploy-ldap

    uses: ./.github/workflows/kubernetes-terraform-deploy-self-hosted-runner.yml
    with:
      terraform-dir: ./terraform/apps/vaultwarden
    secrets: inherit

  # deploy-nextcloud:
  #   needs: deploy-ldap

  #   uses: ./.github/workflows/kubernetes-terraform-deploy-self-hosted-runner.yml
  #   with:
  #     terraform-dir: ./terraform/apps/nextcloud
  #   secrets: inherit
