name: Deploy
on:
  workflow_dispatch:
    inputs:
      runner-type:
        description: 'Runners to use'
        required: true
        default: self-hosted
        type: choice
        options:
          - self-hosted
          - ubuntu-latest
      disaster-recovery:
        description: 'Disaster recovery'
        required: true
        default: false
        type: boolean

jobs:
  deploy-terraform-state-namespace:
    uses: ./.github/workflows/kubernetes-manifest-deploy.yml
    secrets: inherit

    with:
      manifest-file: ./terraform/terraform-state-namespace.yml
      runner-type: ${{ github.event.inputs.runner-type }}

  deploy-github-org-runner-1:
    needs: [
      deploy-terraform-state-namespace,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/github-org-runners-1
      runner-type: ${{ github.event.inputs.runner-type }}

  deploy-github-org-runner-2:
    needs: [
      deploy-github-org-runner-1,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/github-org-runners-2
      runner-type: ${{ github.event.inputs.runner-type }}

  deploy-traefik:
    needs: [
      deploy-terraform-state-namespace,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/traefik
      runner-type: ${{ github.event.inputs.runner-type }}

  deploy-velero:
    needs: [
      deploy-github-org-runner-2,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/velero
      runner-type: ${{ github.event.inputs.runner-type }}

  deploy-loki:
    needs: [
      deploy-github-org-runner-2,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/loki
      runner-type: ${{ github.event.inputs.runner-type }}

  deploy-services:
    needs: [
      deploy-github-org-runner-2,
      deploy-traefik,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/services
      runner-type: ${{ github.event.inputs.runner-type }}

  deploy-openldap:
    needs: [
      deploy-github-org-runner-2,
      deploy-traefik,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/openldap
      runner-type: ${{ github.event.inputs.runner-type }}

  deploy-keycloak:
    needs: [
      deploy-github-org-runner-2,
      deploy-traefik,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/keycloak
      runner-type: ${{ github.event.inputs.runner-type }}

  deploy-harbor:
    needs: [
      deploy-github-org-runner-2,
      deploy-traefik,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/harbor
      runner-type: ${{ github.event.inputs.runner-type }}

  deploy-keycloak-config:
    needs: [
      deploy-openldap,
      deploy-keycloak,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/keycloak-config
      runner-type: ${{ github.event.inputs.runner-type }}

  deploy-vaultwarden:
    needs: [
      deploy-openldap,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/vaultwarden
      runner-type: ${{ github.event.inputs.runner-type }}

  deploy-ocis:
    needs: [
      deploy-keycloak-config,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/ocis
      runner-type: ${{ github.event.inputs.runner-type }}

  deploy-grafana:
    needs: [
      deploy-loki,
      deploy-keycloak-config,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/grafana
      runner-type: ${{ github.event.inputs.runner-type }}

  deploy-harbor-config:
    needs: [
      deploy-harbor,
      deploy-keycloak-config,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/harbor-config
      runner-type: ${{ github.event.inputs.runner-type }}

  deploy-oauth2-proxy:
    needs: [
      deploy-keycloak-config,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/oauth2-proxy
      runner-type: ${{ github.event.inputs.runner-type }}

  deploy-forward-auth-test:
    needs: [
      deploy-oauth2-proxy,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    with:
      terraform-dir: ./terraform/forward-auth-test
      runner-type: ${{ github.event.inputs.runner-type }}

  deploy-velero-restore:
    needs: [
      deploy-velero,
      deploy-services,
      deploy-vaultwarden,
      deploy-ocis,
      deploy-grafana,
      deploy-harbor-config,
      deploy-forward-auth-test,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit
    if: true == inputs.disaster-recovery

    with:
      terraform-dir: ./terraform/velero
      extra-variable: restore_mode=true
      runner-type: ${{ github.event.inputs.runner-type }}
