name: Disaster Recovery
on:
  workflow_dispatch:

jobs:
  deploy-foundational-services:
    uses: ./.github/workflows/deploy-foundational-services.yml
    secrets: inherit

  # deploy storage (and only storage)
  deploy-services-storage:
    needs: deploy-foundational-services

    uses: ./.github/workflows/kubernetes-terraform-deploy-self-hosted-runner.yml
    with:
      terraform-dir: ./terraform/apps/services
      resource-name: truenas_dataset.apps_dataset
    secrets: inherit

  deploy-openldap-storage:
    needs: deploy-foundational-services

    uses: ./.github/workflows/kubernetes-terraform-deploy-self-hosted-runner.yml
    with:
      terraform-dir: ./terraform/apps/openldap
      resource-name: truenas_dataset.openldap
    secrets: inherit

  deploy-vaultwarden-storage:
    needs: deploy-foundational-services

    uses: ./.github/workflows/kubernetes-terraform-deploy-self-hosted-runner.yml
    with:
      terraform-dir: ./terraform/apps/vaultwarden
      resource-name: truenas_dataset.vaultwarden_dataset
    secrets: inherit

  deploy-ocis-nats-storage:
    needs: deploy-foundational-services

    uses: ./.github/workflows/kubernetes-terraform-deploy-specific-resource-self-hosted-runner.yml
    with:
      terraform-dir: ./terraform/apps/ocis
      resource-name: truenas_dataset.ocis_nats_dataset
    secrets: inherit

  deploy-ocis-search-storage:
    needs: deploy-ocis-nats-storage

    uses: ./.github/workflows/kubernetes-terraform-deploy-specific-resource-self-hosted-runner.yml
    with:
      terraform-dir: ./terraform/apps/ocis
      resource-name: truenas_dataset.ocis_search_dataset
    secrets: inherit

  deploy-ocis-storagesystem-storage:
    needs: deploy-ocis-search-storage

    uses: ./.github/workflows/kubernetes-terraform-deploy-specific-resource-self-hosted-runner.yml
    with:
      terraform-dir: ./terraform/apps/ocis
      resource-name: truenas_dataset.ocis_storagesystem_dataset
    secrets: inherit

  deploy-ocis-storageusers-storage:
    needs: deploy-ocis-storagesystem-storage

    uses: ./.github/workflows/kubernetes-terraform-deploy-specific-resource-self-hosted-runner.yml
    with:
      terraform-dir: ./terraform/apps/ocis
      resource-name: truenas_dataset.ocis_storagusers_dataset
    secrets: inherit

  deploy-ocis-store-storage:
    needs: deploy-ocis-storageusers-storage

    uses: ./.github/workflows/kubernetes-terraform-deploy-specific-resource-self-hosted-runner.yml
    with:
      terraform-dir: ./terraform/apps/ocis
      resource-name: truenas_dataset.ocis_store_dataset
    secrets: inherit

  deploy-ocis-thumbnails-storage:
    needs: deploy-ocis-store-storage

    uses: ./.github/workflows/kubernetes-terraform-deploy-specific-resource-self-hosted-runner.yml
    with:
      terraform-dir: ./terraform/apps/ocis
      resource-name: truenas_dataset.ocis_thumbnails_dataset
    secrets: inherit

  deploy-ocis-web-storage:
    needs: deploy-ocis-thumbnails-storage

    uses: ./.github/workflows/kubernetes-terraform-deploy-specific-resource-self-hosted-runner.yml
    with:
      terraform-dir: ./terraform/apps/ocis
      resource-name: truenas_dataset.ocis_web_dataset
    secrets: inherit

  # wait for backup data to be restored into the new storage (manual process with approval through an issue)
  wait-for-data-restore:
    runs-on: self-hosted
    needs: [deploy-services-storage, deploy-openldap-storage, deploy-vaultwarden-storage, deploy-ocis-web-storage]

    permissions:
      issues: write
      contents: write

    steps:
      - name: "Setup node"
        uses: actions/setup-node@v2
      - name: "Wait for approval"
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: jd-chapman
          minimum-approvals: 1
          issue-title: "Restore backup data to new storage"
          issue-body: "Please approve this issue (reply 'approved' or similar) after backup data has been restored to the new storage."
          exclude-workflow-initiator-as-approver: false
  # once approved, deployment can happen as normal
      - name: "Start normal deployment"
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: deployment
