name: Nightly Backup
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 2 * * *'

env:
  CLIENT_CERT_DATA: ${{ secrets.KUBE_CLIENT_CERT_DATA }}
  CLIENT_KEY_DATA: ${{ secrets.KUBE_CLIENT_KEY_DATA }}
  CLUSTER_CA_CERT_DATA: ${{ secrets.KUBE_CLUSTER_CA_CERT_DATA }}
  SERVER_KUBE_PORT: ${{ vars.SERVER_KUBE_PORT }}
  SERVER_BASE_DOMAIN: ${{ vars.SERVER_BASE_DOMAIN }}

jobs:
  check-server-up:
    runs-on: ubuntu-latest

    steps:
      - name: Get server status
        run: curl --max-time 5 https://ping.${{ vars.SERVER_BASE_DOMAIN }}

  # if something depends on one of the services in 'hibernate-databases-2' it has to go here
  hibernate-databases-1:
    needs: [
      check-server-up,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    strategy:
      fail-fast: false
      matrix:
        # it would be nice to dynamically find these
        database: [
          outline,
          penpot,
        ]

    with:
      terraform-dir: ./terraform/${{ matrix.database }}

  hibernate-databases-2:
    needs: [
      hibernate-databases-1,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    strategy:
      fail-fast: false
      matrix:
        # it would be nice to dynamically find these
        database: [
          harbor,
          keycloak,
          vaultwarden,
        ]

    with:
      terraform-dir: ./terraform/${{ matrix.database }}
      extra-variable: is_db_hibernate=true

  start-velero-backup:
    needs: [
      hibernate-databases-2,
    ]
    runs-on: self-hosted

    steps:
      - name: "Repo checkout"
        uses: actions/checkout@v4
      - name: "Add cluster CA certificate"
        run: "echo $CLUSTER_CA_CERT_DATA > cluster.cert.pem && sudo mkdir /usr/local/share/ca-certificates/extra && sudo cp cluster.cert.pem /usr/local/share/ca-certificates/extra/cluster.cert.crt && sudo update-ca-certificates"
      - name: "Generate and install kubeconfig"
        working-directory: ./terraform
        run: |
          ./cluster-config-write.sh
          mkdir ~/.kube
          cp cluster.yml ~/.kube/config
      - name: "Setup kubectl"
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.30.4'
      - name: "Install Velero CLI"
        env:
          VELERO_VERSION: 'v1.13.2'
        run: |
          mkdir velero
          curl https://github.com/vmware-tanzu/velero/releases/download/${{ env.VELERO_VERSION }}/velero-${{ env.VELERO_VERSION }}-linux-amd64.tar.gz -Lo velero.tar.gz
          tar -xvf velero.tar.gz -C ./velero --strip-components=1
          sudo cp ./velero/velero /usr/local/bin/velero
      - name: "Start backup"
        run: velero create backup --from-schedule nightly
      - name: "Wait some time for snapshots"
        run: sleep 300

  restart-databases-1:
    needs: [
      start-velero-backup,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    strategy:
      fail-fast: false
      matrix:
        # it would be nice to dynamically find these
        database: [
          harbor,
          keycloak,
          vaultwarden,
        ]

    with:
      terraform-dir: ./terraform/${{ matrix.database }}

  # if something depends on one of the services in 'restart-databases-1' it has to go here
  restart-databases-2:
    needs: [
      restart-databases-1,
    ]
    uses: ./.github/workflows/kubernetes-terraform-deploy.yml
    secrets: inherit

    strategy:
      fail-fast: false
      matrix:
        # it would be nice to dynamically find these
        database: [
          outline,
          penpot,
        ]

    with:
      terraform-dir: ./terraform/${{ matrix.database }}
